ALTER TABLE companies ADD COLUMN IF NOT EXISTS price NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS price_change_pct NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS volume BIGINT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS market_cap BIGINT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS price_updated_at TIMESTAMPTZ;
