ALTER TABLE companies ADD COLUMN IF NOT EXISTS week_52_high NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS week_52_low NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS day_high NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS day_low NUMERIC;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS volume BIGINT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS long_name TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS cash_position BIGINT;
